version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DB_URL: jdbc:postgresql://db:5432/librarydb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
